export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';

export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST';
export const RESET_PASSWORD_FAILURE = 'RESET_PASSWORD_FAILURE';

export const REQUEST_PASSWORD_REQUEST = 'REQUEST_PASSWORD_REQUEST';
export const REQUEST_PASSWORD_FAILURE = 'REQUEST_PASSWORD_FAILURE';
export const REQUEST_PASSWORD_SUCCESS = 'REQUEST_PASSWORD_SUCCESS';

export const GET_ARTICLE_REQUEST = 'GET_ARTICLE_REQUEST';
export const GET_ARTICLE_SUCCESS = 'GET_ARTICLE_SUCCESS';
export const GET_ARTICLE_FAILURE = 'GET_ARTICLE_FAILURE';

export const ARTICLE_LIKE_REQUEST = 'ARTICLE_LIKE_REQUEST';
export const ARTICLE_LIKE_SUCCESS = 'ARTICLE_LIKE_SUCCESS';

export const ARTICLE_DISLIKE_REQUEST = 'ARTICLE_DISLIKE_REQUEST';
export const ARTICLE_DISLIKE_SUCCESS = 'ARTICLE_DISLIKE_SUCCESS';
