export const SUCCESS = 'SUCCESS';
export const REQUEST = 'REQUEST';
export const FAILURE = 'FAILURE';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST';
export const RESET_PASSWORD_FAILURE = 'RESET_PASSWORD_FAILURE';
export const REQUEST_PASSWORD_REQUEST = 'REQUEST_PASSWORD_REQUEST';
export const REQUEST_PASSWORD_FAILURE = 'REQUEST_PASSWORD_FAILURE';
export const REQUEST_PASSWORD_SUCCESS = 'REQUEST_PASSWORD_SUCCESS';

export const USER_FOLLOWER_REQUEST = 'USER_FOLLOWER_REQUEST';
export const USER_FOLLOWER_SUCCESS = 'USER_FOLLOWER_SUCCESS';
export const USER_FOLLOWER_FAILURE = 'USER_FOLLOWER_FAILURE';
export const USER_FOLLOWING_REQUEST = 'USER_FOLLOWING_REQUEST';
export const USER_FOLLOWING_SUCCESS = 'USER_FOLLOWING_SUCCESS';
export const USER_FOLLOWING_FAILURE = 'USER_FOLLOWING_FAILURE';

export const UNFOLLOW_REQUEST = 'UNFOLLOW_REQUEST';
export const UNFOLLOW_SUCCESS = 'UNFOLLOW_SUCCESS';
export const UNFOLLOW_FAILURE = 'UNFOLLOW_FAILURE';

export const FOLLOW_REQUEST = 'FOLLOW_REQUEST';
export const FOLLOW_SUCCESS = 'FOLLOW_SUCCESS';
export const FOLLOW_FAILURE = 'FOLLOW_FAILURE';
