export const GET_USER_DETAILS='GET_USER_DETAILS';
export const GET_USER_ARTICLES='GET_USER_ARTICLES';
export const GET_USER_DATA_LOADING='GET_USER_DATA_LOADING';
export const GET_USER_ARTICLES_LOADING='GET_USER_ARTICLES_LOADING';
